### ISSUE TITLE
Update the Function names to snake_case.

### ISSUE THREAD

**Issue by sairam4123** [pysamp/PySAMP#46]
Hello, I've found this helpful but the problem is that, this library doesn't follow PEP-8, which recommends the usage of snake_case instead of camelCase or CaptialCase for function names, hope you fix it.

Thank you.

**Comment by dennorske** [comment]
Hi Sairam!

Thanks for the notice. I do strongly believe this is by design, to make converting the gamemodes over to Python a little bit less of a hassle, and the functions recognisable in the SA-MP documentation. We keep past developers in mind coming from Pawn, and that are familiar with the function names.

For someone coming to sa-mp with little prior knowledge, it may look weird.

I will discuss with @habecker and see what we end up doing, however, I am not 100% sure we will action this issue. Thanks for bringing it up.

I'm happy to hear you find it helpful though!

**Comment by habecker** [comment]
Hey Sairam, this is indeed a good suggestion! It's probably a good idea to revise the pysamp.py module and keeping it compatible to CamelCase (at least for some limited time). The same could be done with the callbacks.

**Comment by sairam4123** [comment]
Well, most of the time, Python Developers use snake_case instead of camelCase, maybe adding support for both would be a great idea too.

**Comment by dennorske** [comment]
WIP in `playerclass-test` branch: https://github.com/habecker/PySAMP/tree/playerclass-test
