### ISSUE TITLE
*NOT BUG* I have ran the PySAMP demo, But how can I compile in PyCharm, it said  "no module named pysamp".

### ISSUE THREAD

**Issue by chenz1hao** [pysamp/PySAMP#60]
Well its not bug just my own question:
I have ran the PySAMP demo successfully, so the gamemode.py under python directory is my game modes now? but how can I compile in PyCharm, it said no module named pysamp and I found there actually do not exist pysamp.py in anywhere you provided. So I cannot compile to test when I create my gamemode.py.
![image](https://user-images.githubusercontent.com/16265544/114311476-7ee38c80-9b21-11eb-82eb-b199c98d4ac5.png)

Thank you for your solution in advance and thanks for all you do about this project.

**Comment by dennorske** [comment]
Hi!

So pysamp is a module the plugin will make available when the server runs (runtime module). 

You cannot compile or run the code you write, outside of the server. In order to test, you can start the samp server according to your distribution, and see from there. 

Let me know if you have any other questions :)

**Comment by chenz1hao** [comment]
> Hi!
> 
> So pysamp is a module the plugin will make available when the server runs (runtime module).
> 
> You cannot compile or run the code you write, outside of the server. In order to test, you can start the samp server according to your distribution, and see from there.
> 
> Let me know if you have any other questions :)

I see, that make sense, thankyou
