### ISSUE TITLE
Free allocated memory using PyMem_Free

### ISSUE THREAD

**Issue by habecker** [pysamp/PySAMP#64]

**Comment by Cheaterman** [comment]
Be mindful of those :-) there's PyMem_Free when you get a C-level datastructure that was allocated on the Python side, but for "most" garbage collection you will probably use Py_DECREF().

As an example - https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_New notice how this function (and some less obvious ones!!!) have a "Return value: new reference" in green? That means Python called Py_INCREF for you, and you absolutely need to call Py_DECREF on those yourself once you're done using them at the C level, otherwise it will cause memory leaks! :smile: 

The documentation does explain that in the introduction, but it _is_ quite long and boring... https://docs.python.org/3/c-api/intro.html#objects-types-and-reference-counts :smile:

**Comment by Cheaterman** [comment]
I'm fairly sure 8853f7b2 closes this :-)
