### ISSUE TITLE
Mixed Pawn and Python code results in input error

### ISSUE THREAD

**Issue by geeede** [pysamp/PySAMP#86]
When using some pawn gamemode and activating the PySamp.so plugin results in a server not responding to slash commands on pawn gamemode such as "/help". I checked it out with different gamemodes, the result is same.

When I remove the PySamp.so in server.cfg gamemode, the server succesfully returned a response for commands. So I guess, it's a pysamp related issue.

**Comment by dennorske** [comment]
Thanks for the report!

Can I know the following details:
1. Did you have any (python) code loaded when pysamp loaded? If yes, is it possible to have a look at it?
2. Which plugin version and python version were you running?
3. Which Linux distro / kernel?
4. Which samp server version? 
5. Any other plugins loaded? 

I will use the information to attempt reproduction of the issue, and also to help me identify possible causes for it, to see if it is a regression or something undocumented on our end.

**Comment by geeede** [comment]
Hello, I used the docker file in the repo. The detailed answer is:
1. Yes, here is the python code that I used, it's the modified version of Python Grandlarc gamemode. I modified it because it was giving error, saying that the python interpreter couldn't find the modules so I wrote few lines python. [python-gamemode.zip](https://github.com/pysamp/PySAMP/files/9002816/python-gamemode.zip)

2. PySAMP plugin version is 2.0.1 and the python version is Python 3.8.10
3. The Linux distro and kernel is Ubuntu 20.04.4 LTS
4. I checked the Dockerfile and it seems it's the samp037svr_R2-1 version.

5. The only plugin was crashdetect plugin which is loaded automatically by the PySAMP.

**Comment by dennorske** [comment]
Thanks a lot for the information!

A note is that the grandlarc port over to python is currently broken and is currently not compatible out of the box with PySAMP 2.0 - that is my fault for not fixing.

**Mainly:**
1. it uses the module `pysamp `while the plugin exposes it as `samp` now.
2. Relative path is not inside the python folder, it is in the server root. By adding `python.[submodulename]` for example, I had to do this for it to import modules:
```py
import random
from python.samp import *
from python.glspawns import *
from python.funcs import *
from python.vars import *
from python.player import *

################################
```
3. The Const function is no longer present, constants should now be loaded directly from the plugin module (ex: `from samp import MAX_PLAYERS`).

I also renamed the `gamemode.py` to `__init__.py` and moved all the grandlarc files into a folder called `python` in the server root directory (under `data` with the docker setup) in order to load it. 

## Regarding the issue

I was able to reproduce the issue you see with the MVP code below;

Python:
```py
from samp import *

def OnGameModeInit():
    SetGameModeText('PyLarc MVP')
    AddPlayerClass(272,1759.0189,-1898.1260,13.5622,266.4503,-1,-1,-1,-1,-1,-1)

def OnGameModeExit():
    return True

def OnPlayerCommandText(playerid, cmdtext):
    print(cmdtext)
    print("python called")

def OnPlayerText(playerid, text):
    return True
```

And, here is pawn:
```cs
#include <a_samp>

main()
{
	print("\n----------------------------------");
	print(" Blank Gamemode by your name here");
	print("----------------------------------\n");
}

public OnGameModeInit()
{
	return 1;
}

public OnGameModeExit()
{
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if (strcmp("/mycommand", cmdtext, true, 10) == 0)
	{
		printf("Well something happened in amx");
		return 1;
	}
	return 0;
}

```
My result running /mycommand only printed the code in Python.

We will get back to you on the potential cause behind this and see if it requires action on our end. Once again, thanks for reporting it!

**Comment by geeede** [comment]
Okay, thanks for everything.

**Comment by dennorske** [comment]
Thanks to @ksenonadv in the PR here; #88 

They figured out what the issue was - essentially, the OnPlayerCommandText would not pass on the callback call to PAWN side, as it had no default return value in python.

You can get around this by adding;
```py
return False
```
on the python side, in the given callback. If it is not added, you can add it to the grandlarc mode;
```py
def OnPlayerCommandText(playerid, cmdtext):
    return False
```

When PR #88 is merged, we will compile a new version of the plugin and add this to our release. It will address occurences where callback returns are not present in python side.

Let me know if it solves your issue 👍

**Comment by geeede** [comment]
> Thanks to @ksenonadv in the PR here; #88
> 
> They figured out what the issue was - essentially, the OnPlayerCommandText would not pass on the callback call to PAWN side, as it had no default return value in python.
> 
> You can get around this by adding;
> 
> ```python
> return False
> ```
> 
> on the python side, in the given callback. If it is not added, you can add it to the grandlarc mode;
> 
> ```python
> def OnPlayerCommandText(playerid, cmdtext):
>     return False
> ```
> 
> When PR #88 is merged, we will compile a new version of the plugin and add this to our release. It will address occurences where callback returns are not present in python side.
> 
> Let me know if it solves your issue 👍

This fixed it. I already tried with

`return True` because other functions was returning true value. But never thought what would happen if it returns false.

It seems like that the problem is solved.
Thank you all!

**Comment by dennorske** [comment]
Thanks for confirming!

To understand more, you need to look at how SA-MP treats the returns in certain callbacks; some need return 1 (True) or 0 (False) to pass on / block the call in other scripts.

For OnPlayerCommandText you can see documentation here; https://team.sa-mp.com/wiki/OnPlayerCommandText.html

Extract:
```cs
public OnPlayerCommandText(playerid, cmdtext[])
{
    if(!strcmp(cmdtext, "/help", true))
    {
        SendClientMessage(playerid, -1, "SERVER: This is the /help command!");
        return 1;
        // Returning 1 informs the server that the command has been processed.
        // OnPlayerCommandText won't be called in other scripts.
    }
    return 0;
    // Returning 0 informs the server that the command hasn't been processed by this script.
    // OnPlayerCommandText will be called in other scripts until one returns 1.
    // If no scripts return 1, the 'SERVER: Unknown Command' message will be shown to the player.
}
```

So when a command is processed in python, you can return `True` to prevent it from being passed on to other scripts where the command may not exist.

**Comment by Cheaterman** [comment]
56cbe13 closes this, thanks a lot for the report!
