### ISSUE TITLE
Use StaticMethods for event receivers/handlers.

### ISSUE THREAD

**Issue by sairam4123** [pysamp/PySAMP#89]
**Is your feature request related to a problem? Please describe.**
No. It's just a usability issue.

**Describe the solution you'd like**
Replace classmethods with staticmethods for event handler.

**Comment by dennorske** [comment]
Due to our design, using staticmethods will not be possible..

What we do with our events, is that we have our event handler get a call from server, and then it delegates the call out to the registered events. Here is our decorator to register new events in a class:
https://github.com/pysamp/PySAMP/blob/f0dbab0a185acf4d714bf2d1925e4a2aa50662b3/pysamp/event.py#L5-L22

As you can see here: 
https://github.com/pysamp/PySAMP/blob/f0dbab0a185acf4d714bf2d1925e4a2aa50662b3/pysamp/player.py#L2630-L2632
the decorator takes the default arguments and converts them over to actual objects representing the class they are in.

So instead of having an event like this (with playerid)
```py
@Player.on_spawn
def player_spawning(playerid: int):
    # use playerid in code, ewww..
```

We want to convert the argument to a player object (in this case) so it becomes like this:
```py
@Player.on_spawn
def player_spawning_new(player: Player):
    # Phew! Much better with the player object.
```

Using static methods for this will not work the way it is being handled. Remember that static methods know nothing about the class state.

**Comment by simeneriks1** [comment]
Actually, due to our design, using staticmethods will not be possible..

What we do with our events, is that we have our event handler get a call from server, and then it delegates the call out to the registered events. Here is our decorator to register new events in a class:
https://github.com/pysamp/PySAMP/blob/f0dbab0a185acf4d714bf2d1925e4a2aa50662b3/pysamp/event.py#L14-L18

As you can see [here](https://github.com/pysamp/PySAMP/blob/f0dbab0a185acf4d714bf2d1925e4a2aa50662b3/pysamp/player.py#L2630-L2632), the decorator takes the default arguments and converts them over to actual objects.

So instead of having an event like this:
```py
@Player.on_spawn
def player_spawning(playerid: int):
    # use playerid in code, ew..
```

We need want to convert the argument to a player object:
```
@Player.on_spawn
def player_spawning_new(player: Player):
    # Phew! Much better with the player object.
```

Using static methods for this will not work the way it is being handled. Remember that static methods know nothing about the class state.

**Comment by Cheaterman** [comment]
Could you perhaps clarify how classmethods are a "usability issue"? staticmethods are generally frowned upon :-)
